server {
    listen 5173;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://api:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Rewrite /api to match backend expectations (which expects /auth, /fhir etc directly if mounted that way)
        # Note: In Vite config, it re-writes /api to empty string.
        rewrite ^/api/(.*) /$1 break;
    }
}
